FROM robcole/crystal:lucky as common-crystal
RUN GO111MODULE=on go install github.com/DarthSim/overmind@v2 \
  && mv /root/go/bin/overmind /usr/local/bin/overmind
RUN git clone https://github.com/luckyframework/lucky_cli . && \
    git checkout v0.30.0 && \
    shards install --without-development && \
    shards build --production && \
    cp bin/lucky /usr/local/bin

FROM node:${NODE_VERSION} AS node

FROM common-crystal
WORKDIR /app
RUN apk add --update --no-cache \
  bash \
  dpkg \
  git \
  gmp-dev \
  postgresql-client \
  tmux \
  yaml-static
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin
ENV DATABASE_URL=${DATABASE_URL}
ENTRYPOINT []
CMD ["/bin/bash"]
