services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: robcole/hirobot:latest
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: postgres_data_hirobot_app
        target: /var/lib/postgresql/data
  baseimage:
    build:
      context: .
      dockerfile: Dockerfile.baseimage
    image: robcole/crystal:1.5.1-hoard

volumes:
  postgres_data_hirobot_app:
  node_modules:
