steps:
  - name: "Build and upload :docker: image"
    command: "ARCH=arm64 script/upload_crystal_base_image.sh"
    agents:
      queue: arm64
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_PROGRESS: plain
    branches: "crystal/*"
    
  - name: "Build and upload :docker: image"
    command: "ARCH=amd64 script/upload_crystal_base_image.sh"
    agents:
      queue: amd64
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_PROGRESS: plain
    branches: "crystal/*"

  - name: "Build and upload :docker: image"
    command: "ARCH=arm64 script/upload_crystal_with_hoard.sh"
    agents:
      queue: arm64
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_PROGRESS: plain
    branches: "main preview/*"

  - name: "Build and upload :docker: image"
    command: "ARCH=amd64 script/upload_crystal_with_hoard.sh"
    agents:
      queue: amd64
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_PROGRESS: plain
    branches: "main preview/*"
