steps:
  - name: "Build and upload :docker: image"
    command: "ARCH=arm64 script/upload_crystal_base_images.sh"
    agents:
      queue: arm64
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_PROGRESS: plain
    branches: "preview/*"
    
  - name: "Build and upload :docker: image"
    command: "ARCH=amd64 script/upload_crystal_base_images.sh"
    agents:
      queue: amd64
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_PROGRESS: plain
    branches: "preview/*"
