name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  LUCKY_ENV: production
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.0
        - uses: superfly/flyctl-actions@v2
          with:
            args: "deploy"
